import 'package:flutter/material.dart';

class HelperAbout {
  HelperAbout._();
  static var aboutCrona = 'Coronavirus disease 2019 (COVID-19) is a contagious disease caused by severe acute respiratory syndrome coronavirus 2 (SARS-CoV-2). The first known case was identified in Wuhan, China in December 2019.[7] The disease has since spread worldwide, leading to an ongoing pandemic\nSARS‑CoV‑2 belongs to the broad family of viruses known as coronaviruses. It is a positive-sense single-stranded RNA (+ssRNA) virus, with a single linear RNA segment. Coronaviruses infect humans, other mammals, and avian species, including livestock and companion animals. Human coronaviruses are capable of causing illnesses ranging from the common cold to more severe diseases such as Middle East respiratory syndrome (MERS, fatality rate ~34%).';
  static var aboutSymptoms1 = 'COVID-19 affects different people in different ways. Most infected people will develop mild to moderate illness and recover without hospitalization';
  static var aboutSymptoms2 = '\nSeek immediate medical attention if you have serious symptoms. Always call before visiting your doctor or health facility.\nPeople with mild symptoms who are otherwise healthy should manage their symptoms at home.\nOn average it takes 5–6 days from when someone is infected with the virus for symptoms to show, however it can take up to 14 days.';
  static var listCommonSymptoms = ['Fever','Dry Cough','Tiredness'];
  static var listLessSymptoms = ['Aches & Pains','Sore throat','Diarrhoea','Conjunctivitis','Headache','Loss of taste or smell','A rash on skin, or discolouration of fingers or toes'];
  static var listSeriousSymptoms = ['Difficulty breathing or shortness of breath','Chest pain or pressure','Loss of speech or movement'];
  static var listPreventation = [
    'Wash your hands regularly with soap and water, or clean them with alcohol-based hand rub',
    'Maintain at least 1 metre distance between you and people coughing or sneezing',
    'Avoid touching your face',
    'Cover your mouth and nose when coughing or sneezing',
    'Stay home if you feel unwell',
    'Refrain from smoking and other activities that weaken the lungs',
    'Practice physical distancing by avoiding unnecessary travel and staying away from large groups of people'
  ];

  static var listIcons = [
    Icon(Icons.groups,color: Colors.teal,size: 35),
    Icon(Icons.content_paste_rounded,color: Colors.blue,size: 35),
    Icon(Icons.verified_user_rounded,color: Colors.green,size: 35),
    Icon(Icons.health_and_safety,color: Colors.amber,size: 35),
    Icon(Icons.hotel,color: Colors.red,size: 35),
    Icon(Icons.gpp_maybe_rounded,color: Colors.red,size: 35),
    Icon(Icons.person_add_alt_sharp,color: Colors.blue,size: 35),
    Icon(Icons.person_add_alt_sharp,color: Colors.red,size: 35),
  ];

  static var listTags = [
    'Population',
    'Confirmed',
    'Recovered',
    'Active',
    'Deaths',
    'Critical',
    'New Cases',
    'New Deaths'
  ];

  static var listIconsVaccine = [
    Icon(Icons.computer_rounded,color: Colors.blue,size: 35),
    Icon(Icons.groups,color: Colors.teal,size: 35),
    Icon(Icons.verified_user_rounded,color: Colors.amber,size: 35),
    Icon(Icons.verified_user_rounded,color: Colors.green,size: 35)
  ];

  static var listVaccineTag = [
    'Registrations',
    'Total Dose',
    'Dose1',
    'Dose2',
  ];

  static var flagCode = {
    "Andorra": "ad",
     "UAE": "ae",
     "Afghanistan": "af",
     "Antigua And Barbuda": "ag",
     "Anguilla": "ai",
     "Albania": "al",
     "Armenia": "am",
     "Netherlands": "an",
     "Angola": "ao",
     "Antarctica": "aq",
     "Argentina": "ar",
     "Samoa": "as",
     "Austria": "at",
     "Australia": "au",
     "Aruba": "aw",
     "Bosnia and Herzegovina": "ba",
     "Barbados": "bb",
     "Bangladesh": "bd",
     "Belgium": "be",
     "Burkina Faso": "bf",
     "Bulgaria": "bg",
     "Bahrain": "bh",
     "Burundi": "bi",
     "Benin": "bj",
     "Bermuda": "bm",
     "Brunei": "bn",
     "Bolivia": "bo",
     "Brazil": "br",
     "Bahamas": "bs",
     "Bhutan": "bt",
     "Botswana": "bw",
     "Belarus": "by",
     "Belize": "bz",
     "Canada": "ca",
     "Congo": "cg",
     "Switzerland": "ch",
     "Ivory Coast": "ci",
     "Chile": "cl",
     "Cameroon": "cm",
     "China": "cn",
     "Colombia": "co",
     "Costa Rica": "cr",
     "Cuba": "cu",
     "Cabo Verde": "cv",
     "Cyprus": "cy",
     "Czech": "cz",
     "Germany": "de",
     "Djibouti": "dj",
     "Denmark": "dk",
     "Dominica": "dm",
     "Dominican Republic": "do",
     "Algeria": "dz",
     "Ecuador": "ec",
     "Estonia": "ee",
     "Egypt": "eg",
     "Western Sahara": "eh",
     "Eritrea": "er",
     "Spain": "es",
     "Ethiopia": "et",
     "Finland": "fi",
     "Fiji": "fj",
     "Falkland Islands": "fk",
     "Micronesia": "fm",
     "France": "fr",
     "Gabon": "ga",
     "UK": "gb",
     "Grenada": "gd",
     "Georgia": "ge",
     "French Guiana": "gf",
     "Ghana": "gh",
     "Gibraltar": "gi",
     "Greenland": "gl",
     "Gambia": "gm",
     "Guinea": "gn",
     "Guadeloupe": "gp",
     "Equatorial Guinea": "gq",
     "Greece": "gr",
     "Guatemala": "gt",
     "Guinea-Bissau": "gw",
     "Guyana": "gy",
     "Hong Kong": "hk",
     "Honduras": "hn",
     "Croatia": "hr",
     "Haiti": "ht",
     "Hungary": "hu",
     "Indonesia": "id",
     "Ireland": "ie",
     "Israel": "il",
     "India": "in",
     "Iraq": "iq",
     "Iran": "ir",
     "Iceland": "is",
     "Italy": "it",
     "Jamaica": "jm",
     "Jordan": "jo",
     "Japan": "jp",
     "Kenya": "ke",
     "Kyrgyzstan": "kg",
     "Cambodia": "kh",
     "Comoros": "km",
     "Saint Kitts and Nevis": "kn",
     "North Korea": "kp",
     "South Korea": "kr",
     "Kuwait": "kw",
     "Cayman Islands": "ky",
     "Kazakhstan": "kz",
     "Laos": "la",
     "Lebanon": "lb",
     "Saint Lucia": "lc",
     "Liechtenstein": "li",
     "Sri Lanka": "lk",
     "Liberia": "lr",
     "Lesotho": "ls",
     "Lithuania": "lt",
     "Luxembourg": "lu",
     "Latvia": "lv",
     "Libya": "ly",
     "Morocco": "ma",
     "Monaco": "mc",
     "Madagascar": "mg",
     "Marshall Islands": "mh",
     "North Macedonia": "mk",
     "Mali": "ml",
     "Myanmar": "mm",
     "Mongolia": "mn",
     "Macao": "mo",
     "Martinique": "mq",
     "Mauritania": "mr",
     "Montserrat": "ms",
     "Malta": "mt",
     "Mauritius": "mu",
     "Maldives": "mv",
     "Malawi": "mw",
     "Mexico": "mx",
     "Malaysia": "my",
     "Mozambique": "mz",
     "Namibia": "na",
     "New Caledonia": "nc",
     "Niger": "ne",
     "Nigeria": "ng",
     "Nicaragua": "ni",
     "Norway": "no",
     "Nepal": "np",
     "New Zealand": "nz",
     "Oman": "om",
     "Panama": "pa",
     "Peru": "pe",
     "French Polynesia": "pf",
     "Papua New Guinea": "pg",
     "Philippines": "ph",
     "Pakistan": "pk",
     "Poland": "pl",
     "Portugal": "pt",
     "Palau": "pw",
     "Paraguay": "py",
     "Qatar": "qa",
     "Reunion": "re",
     "Romania": "ro",
     "Russia": "ru",
     "Rwanda": "rw",
     "Saudi Arabia": "sa",
     "Solomon Islands": "sb",
     "Seychelles": "sc",
     "Sudan": "sd",
     "Sweden": "se",
     "Singapore": "sg",
     "Saint Helena": "sh",
     "Slovenia": "si",
     "Slovakia": "sk",
     "Sierra Leone": "sl",
     "San Marino": "sm",
     "Senegal": "sn",
     "Somalia": "so",
     "Suriname": "sr",
     "Sao Tome and Principe": "st",
     "El Salvador": "sv",
     "Syria": "sy",
     "Swaziland": "sz",
     "Chad": "td",
     "Togo": "tg",
     "Thailand": "th",
     "Tajikistan": "tj",
     "Tunisia": "tn",
     "Turkey": "tr",
     "Trinidad And Tobago": "tt",
     "Taiwan": "tw",
     "Tanzania": "tz",
     "Ukraine": "ua",
     "Uganda": "ug",
     "USA": "us",
     "Uruguay": "uy",
     "Uzbekistan": "uz",
     "Vatican City": "va",
     "St. Vincent Grenadines": "vc",
     "Venezuela": "ve",
     "British Virgin Islands": "vg",
     "Vietnam": "vn",
     "Vanuatu": "vu",
     "Wallis and Futuna": "wf",
     "Yemen": "ye",
     "Mayotte": "yt",
     "South Africa": "za",
     "Zambia": "zm",
     "Zimbabwe": "zw"
  };
}
