// File generated by FlutterFire CLI.
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      // case TargetPlatform.iOS:
      //   return ios;
      // case TargetPlatform.macOS:
      //   return macos;
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: "AIzaSyBsTkU3hx4cIh4ZchyeANufjg9ExH4iyRw",
    authDomain: "flutterpushnotification-81515.firebaseapp.com",
    databaseURL: "https://flutterpushnotification-81515-default-rtdb.firebaseio.com",
    projectId: "flutterpushnotification-81515",
    storageBucket: "flutterpushnotification-81515.appspot.com",
    messagingSenderId: "1066275591079",
    appId: "1:1066275591079:web:88d81ecee1c8f34e201c82",
    measurementId: "G-4DCHB33PDQ"
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDrBreohrQS942n0wxohazQ9yyw-NAYr_A',
    appId: '1:1066275591079:android:340ea0fe21e3e961201c82',
    messagingSenderId: '1066275591079',
    projectId: 'flutterpushnotification-81515',
    databaseURL: 'https://flutterpushnotification-81515-default-rtdb.firebaseio.com',
    storageBucket: 'flutterpushnotification-81515.appspot.com',
  );

  // static const FirebaseOptions ios = FirebaseOptions(
  //   apiKey: 'AIzaSyAHAsf51D0A407EklG1bs-5wA7EbyfNFg0',
  //   appId: '1:448618578101:ios:0b11ed8263232715ac3efc',
  //   messagingSenderId: '448618578101',
  //   projectId: 'react-native-firebase-testing',
  //   databaseURL: 'https://react-native-firebase-testing.firebaseio.com',
  //   storageBucket: 'react-native-firebase-testing.appspot.com',
  //   androidClientId:
  //       '448618578101-a9p7bj5jlakabp22fo3cbkj7nsmag24e.apps.googleusercontent.com',
  //   iosClientId:
  //       '448618578101-evbjdqq9co9v29pi8jcua8bm7kr4smuu.apps.googleusercontent.com',
  //   iosBundleId: 'io.flutter.plugins.firebase.messaging',
  // );

  // static const FirebaseOptions macos = FirebaseOptions(
  //   apiKey: 'AIzaSyAHAsf51D0A407EklG1bs-5wA7EbyfNFg0',
  //   appId: '1:448618578101:ios:0b11ed8263232715ac3efc',
  //   messagingSenderId: '448618578101',
  //   projectId: 'react-native-firebase-testing',
  //   databaseURL: 'https://react-native-firebase-testing.firebaseio.com',
  //   storageBucket: 'react-native-firebase-testing.appspot.com',
  //   androidClientId:
  //       '448618578101-a9p7bj5jlakabp22fo3cbkj7nsmag24e.apps.googleusercontent.com',
  //   iosClientId:
  //       '448618578101-evbjdqq9co9v29pi8jcua8bm7kr4smuu.apps.googleusercontent.com',
  //   iosBundleId: 'io.flutter.plugins.firebase.messaging',
  // );
}