name: flutterapp
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.2.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  toast: ^0.1.5
  shared_preferences: ^0.5.7
  http: ^0.12.0+4
  google_maps_flutter: ^0.5.26+4
  location_permissions: ^2.0.5
  location: ^2.5.0
  geolocator: ^5.3.0
  permissions_plugin: ^1.1.4
  permission_handler: '^4.4.0+hotfix.2'
  progress_dialog: ^1.2.1
  url_launcher: ^5.4.2
  email_validator: '^1.0.0'
  video_player: ^0.7.2
  flutter_datetime_picker: ^1.3.5
  badges: ^1.1.1
  geocoder: ^0.2.1
  flutter_google_places: ^0.2.4
  google_maps_webservice: ^0.0.16
  dio: ^3.0.9
  flutter_launcher_icons: ^0.7.4
  countdown: ^0.1.0
  

module:
  androidX: true

dev_dependencies:

  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true


  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg
  assets:
    - assets/images/about_device.png
    - assets/images/interval.png
    - assets/images/monitoring.png
    - assets/images/password.png
    - assets/images/power_off.png
    - assets/images/reboot.png 
    - assets/images/follohlogo.jpg
    - assets/images/follohbanner.jpg
    - assets/images/banner.png
    - assets/images/app_icon.png
    - assets/images/doglanding.png
    - assets/images/Geofence.png
    - assets/images/historical.png
    - assets/images/Real_time.png
    - assets/images/settings.png
    - assets/images/reset.png
    - assets/images/signal_light.png
    - assets/images/sos_list.png
    - assets/images/sensor_light.png
    - assets/images/cat_marker.png
    - assets/images/dog_marker.png


  fonts:
    - family: MontserratBlack
      fonts:
        - asset: assets/fonts/Montserrat-Black.ttf
    - family: MontserratBold
      fonts:
        - asset: assets/fonts/Montserrat-Bold.ttf
    - family: MontserratExtraBold
      fonts:
        - asset: assets/fonts/Montserrat-ExtraBold.ttf
    - family: MontserratExtraLight
      fonts:
        - asset: assets/fonts/Montserrat-ExtraLight.ttf
    - family: MontserratLight
      fonts:
        - asset: assets/fonts/Montserrat-Light.ttf
    - family: MontserratMedium
      fonts:
        - asset: assets/fonts/Montserrat-Medium.ttf
    - family: MontserratRegular
      fonts:
        - asset: assets/fonts/Montserrat-Regular.ttf
    - family: MontserratSemiBold
      fonts:
        - asset: assets/fonts/Montserrat-SemiBold.ttf 
    - family: MontserratThin
      fonts:
        - asset: assets/fonts/Montserrat-Thin.ttf               


flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/app_icon.png"
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
